services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.6
    command: start-dev --import-realm
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    volumes:
      - ./testrealm.json:/opt/keycloak/data/import/testrealm.json
