name: Release Build
on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Determine tag name
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]
          then
            echo TAG_NAME=snapshot >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]
          then
            echo TAG_NAME=snapshot-develop >> $GITHUB_ENV
          else
            echo TAG_NAME=`basename ${{ github.ref }}` >> $GITHUB_ENV
          fi

      - name: Create tarball
        run: |
          mv dist scigateway-$TAG_NAME
          tar -czf scigateway-$TAG_NAME.tar.gz scigateway-$TAG_NAME

      - name: Update snapshot tag
        uses: richardsimko/update-tag@aab2434e9a5040687874aa39d1c6377ec0cb0d94 # v1
        with:
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}

      - name: Create/update release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./scigateway-${{ env.TAG_NAME }}.tar.gz
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
          draft: false
          generate_release_notes: true
